###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class InitialResponse(BaseModel):
    action: Optional[Union[Literal["TO_INITIAL"], Literal["TO_SHARING"]]] = None
    name: Optional[str] = None
    explain_reasoning_to_rallie: Optional[str] = None
    message_draft: Optional[str] = None
    message_critique: Optional[str] = None
    message: Optional[str] = None
    previous_user_message_topic: Optional[str] = None
    topic_critique: Optional[str] = None
    final_topic: Optional[str] = None

class Message(BaseModel):
    role: Optional[str] = None
    content: Optional[str] = None

class OffTool(BaseModel):
    action: Optional[Literal["off"]] = None

class OnTool(BaseModel):
    action: Optional[Literal["on"]] = None

class Resume(BaseModel):
    name: Optional[str] = None
    email: Optional[str] = None
    experience: List[str]
    skills: List[str]

class SharingResponse(BaseModel):
    action: Optional[Literal["TO_SHARING"]] = None
    name: Optional[str] = None
    explain_reasoning_to_rallie: Optional[str] = None
    message_draft: Optional[str] = None
    message_critique: Optional[str] = None
    message: Optional[str] = None
    previous_user_message_topic: Optional[str] = None
    topic_critique: Optional[str] = None
    final_topic: Optional[str] = None
