###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Literal, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class InitialResponse(BaseModel):
    action: Union[Literal["TO_INITIAL"], Literal["TO_SHARING"]]
    name: Optional[str] = None
    explain_reasoning_to_rallie: str
    message_draft: str
    message_critique: str
    message: str
    previous_user_message_topic: str
    topic_critique: str
    final_topic: str

class Message(BaseModel):
    role: str
    content: str

class OffTool(BaseModel):
    action: Literal["off"]

class OnTool(BaseModel):
    action: Literal["on"]

class Resume(BaseModel):
    name: str
    email: str
    experience: List[str]
    skills: List[str]

class SharingResponse(BaseModel):
    action: Literal["TO_SHARING"]
    explain_reasoning_to_rallie: str
    message_draft: str
    message_critique: str
    message: str
    previous_user_message_topic: str
    topic_critique: str
    final_topic: str
